/* eslint-disable react/jsx-filename-extension */
import React from 'react';

import Head from 'next/head';
// import Image from 'next/image';
// import wordmarkLogo from '../public/wordmark_logo.png';
import { Text } from '@nextui-org/react';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Mr. Please</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Text h1>Coming Soon</Text>
                {/*  <Image
                    src={wordmarkLogo}
                    width="306"
                    height="396"
                    className="hvr-hang"
                /> */}
            </main>
        </div>
    );
}
