/* eslint-disable react/jsx-filename-extension */
import React from 'react';

import Head from 'next/head';
// import Image from 'next/image';
// import wordmarkLogo from '../public/wordmark_logo.png';
// import { Text } from '@nextui-org/react';
import { Text, Card, Button, Spacer } from '@nextui-org/react';

import Nav from '../components/Navbar';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Mr. Please</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />

            <main className="w-full flex flex-col justify-center items-center mt-24">
                <Card
                    isHoverable
                    variant="bordered"
                    css={{ mw: '1000px' }}
                    className="mb-8"
                >
                    <Card.Body>
                        <div className="flex justify-between items-center">
                            <Text h2>Feb 24</Text>
                            <Text>Louisville, KY</Text>
                            <Text>Gravely Brewing Co.</Text>
                            <Button auto color="secondary" rounded flat>
                                Tickets
                            </Button>
                        </div>
                    </Card.Body>
                </Card>
                <Spacer h={2} />
                <Card
                    isHoverable
                    variant="bordered"
                    css={{ mw: '1000px' }}
                    className="mb-8"
                >
                    <Card.Body>
                        <div className="flex justify-between items-center">
                            <Text h2>Mar 17</Text>
                            <Text>Louisville, KY</Text>
                            <Text>Zanzabar</Text>
                            <Button auto color="secondary" rounded flat>
                                Tickets
                            </Button>
                        </div>
                    </Card.Body>
                </Card>
                <Spacer h={2} />

                <Card
                    isHoverable
                    variant="bordered"
                    css={{ mw: '1000px' }}
                    className="mb-8"
                >
                    <Card.Body>
                        <div className="flex justify-between items-center">
                            <Text h2>Mar 24</Text>
                            <Text>Louisville, KY</Text>
                            <Text>Vernon Lanes</Text>
                            <Button auto color="secondary" rounded flat>
                                Tickets
                            </Button>
                        </div>
                    </Card.Body>
                </Card>
                <Spacer h={2} />

                <Card
                    isHoverable
                    variant="bordered"
                    css={{ mw: '1000px' }}
                    className="mb-8"
                >
                    <Card.Body>
                        <div className="flex justify-between items-center">
                            <Text h2>Apr 28</Text>
                            <Text>Covington, KY</Text>
                            <Text>Madison Live!</Text>
                            <Button auto color="secondary" rounded flat>
                                Tickets
                            </Button>
                        </div>
                    </Card.Body>
                </Card>
            </main>
        </div>
    );
}
